### ISSUE TITLE
Can't use jenkins-jack commands

### ISSUE THREAD

**Issue by pault1337** [tabeyti/jenkins-jack#8] opened 2019-09-13 09:01 UTC
Hi,

I installed your extension and filled the extension settings in the settings.json as explained in the documentation. Unfortunately, I can't make it work. Every jenkins-jack command returns an error message like "command 'extension.jenkins-jack.jacks' not found".

![jenkins-jack-error-msg](https://user-images.githubusercontent.com/8106841/64850107-11097300-d615-11e9-9536-75f78f106780.png)

Am I missing something?
Thanks in advance for your help.
Regards,

Paul

**Comment by carter-clearlabs** [comment] 2019-09-18 05:06
Having similar issue as @pault1337 - Tool looks amazing - can't wait to try it out.

**Comment by n-roman** [comment] 2019-09-19 09:03
The same problem. VsCode 1.38.1, extension 0.1.5

**Comment by tabeyti** [comment] 2019-09-19 19:03
Hey @pault1337 , @carter-clearlabs , and @n-roman !

Apologies for the late reply. I _think_ the issue is that the commands don't display unless you are in an active text view that has `groovy` language mode.

I have a fix for this which I'll try to shoot out tonight. 

In the interim, can one of you validate this is the case by opening an actual `.groovy` file and executing the keyboard shortcut `ctrl+shift+j`?

**Comment by tabeyti** [comment] 2019-09-20 07:00
Fix should be in 0.1.6

[Changelog](https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md)

Keeping the issue open until someone is able to verify the fix.

**Comment by n-roman** [comment] 2019-09-20 08:38
@tabeyti I can confirm that commands work in `groovy` language mode in 1.5. And I tested 1.6 just now, the bug is fixed. Thank you!

**Comment by pault1337** [comment] 2019-09-20 08:44
@tabeyti same here. Works with 1.5 in `groovy` language mode. Thanks ! Extension looks awesome !

**Comment by betterversion** [comment] 2019-09-20 16:18
@tabeyti @tabeyti The default keybinding  overrides  Jacks keybinding istead I get _editor.remove-line-underneath_ . Is the way to provide it explicitly. Thanks

**Comment by tabeyti** [comment] 2019-09-21 17:57
@n-roman and @pault1337 ,

Thanks for checking that. You guys rock!

@betterversion ,

If the command is being overwritten by another keyboard shortcut, you can change this by reassigning the hot keys for the `jenkins-jack.jacks` command to something different:

https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts

If i'm wrong and this isn't the problem you are experiencing, open another issue with the deets and we'll figure it out.

Closing this ticket as the issue for the original request has been fixed.

**Closed by tabeyti** 2019-09-21 17:57 UTC
Labels: bug

**Comment by har0ns** [comment] 2020-01-05 10:11
Hi.
v1.0.1 and v1.0.1  jenkins-jack command returns an error message like "command 'extension.jenkins-jack.jacks' not found".
v0.1.6 jenkins-jack command it's working.
VSCode v 1.41.1

**Comment by jdhzzz** [comment] 2020-04-27 10:28
Hi,
I am using code Version: 1.44.2.  I run 1.0.1 and it reports 'extension.jenkins-jack.jacks' not found.  If I select 0.16, it works (?!).
